#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.android.ex.chips.Resource", IsApplication=false)]

namespace com.android.ex.chips
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int avatarPosition = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int chipBackground = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int chipBackgroundPressed = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int chipDelete = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int chipEntryErrorHint = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int chipFontSize = 2130771972;
			
			// aapt resource value: 0x7f010007
			public static int chipHeight = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int chipOverLimitErrorHint = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int chipPadding = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int disableDelete = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public static int imageSpanAlignment = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int invalidChipBackground = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public static int chip_height = 2130968577;
			
			// aapt resource value: 0x7f040007
			public static int chip_icon_margin_start = 2130968583;
			
			// aapt resource value: 0x7f040000
			public static int chip_padding = 2130968576;
			
			// aapt resource value: 0x7f040006
			public static int chip_subtitle_padding_start = 2130968582;
			
			// aapt resource value: 0x7f040002
			public static int chip_text_size = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int chip_title_padding_start = 2130968581;
			
			// aapt resource value: 0x7f040004
			public static int extra_chip_height = 2130968580;
			
			// aapt resource value: 0x7f040003
			public static int line_spacing_extra = 2130968579;
			
			// aapt resource value: 0x7f040008
			public static int padding_no_picture = 2130968584;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int chip_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int chip_background_invalid = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int chip_background_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int chip_delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ic_contact_picture = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int list_item_font_primary = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int list_item_font_secondary = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int no_avatar_picture = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public static int baseline = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int bottom = 2131230723;
			
			// aapt resource value: 0x7f080000
			public static int end = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int start = 2131230721;
			
			// aapt resource value: 0x7f080004
			public static int text1 = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public static int chips_max_lines = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int chips_alternate_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int chips_recipient_dropdown_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int copy_chip_dialog_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int more_item = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060003
			public static int copy_email = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int copy_number = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int done = 2131099653;
			
			// aapt resource value: 0x7f060001
			public static int error_invalid_chips = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int error_over_chips_limit = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int more_string = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070003
			public static int ChipIconStyle = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int ChipSubtitleStyle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public static int ChipTitleStyle = 2131165185;
			
			// aapt resource value: 0x7f070000
			public static int RecipientEditTextView = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecipientEditTextView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public static int RecipientEditTextView_avatarPosition = 0;
			
			// aapt resource value: 1
			public static int RecipientEditTextView_chipBackground = 1;
			
			// aapt resource value: 2
			public static int RecipientEditTextView_chipBackgroundPressed = 2;
			
			// aapt resource value: 3
			public static int RecipientEditTextView_chipDelete = 3;
			
			// aapt resource value: 5
			public static int RecipientEditTextView_chipEntryErrorHint = 5;
			
			// aapt resource value: 4
			public static int RecipientEditTextView_chipFontSize = 4;
			
			// aapt resource value: 7
			public static int RecipientEditTextView_chipHeight = 7;
			
			// aapt resource value: 6
			public static int RecipientEditTextView_chipOverLimitErrorHint = 6;
			
			// aapt resource value: 8
			public static int RecipientEditTextView_chipPadding = 8;
			
			// aapt resource value: 9
			public static int RecipientEditTextView_disableDelete = 9;
			
			// aapt resource value: 11
			public static int RecipientEditTextView_imageSpanAlignment = 11;
			
			// aapt resource value: 10
			public static int RecipientEditTextView_invalidChipBackground = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
