#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Test.Droid.Resource", IsApplication=true)]

namespace Test.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.android.ex.chips.Resource.Attribute.avatarPosition = global::Test.Droid.Resource.Attribute.avatarPosition;
			global::com.android.ex.chips.Resource.Attribute.chipBackground = global::Test.Droid.Resource.Attribute.chipBackground;
			global::com.android.ex.chips.Resource.Attribute.chipBackgroundPressed = global::Test.Droid.Resource.Attribute.chipBackgroundPressed;
			global::com.android.ex.chips.Resource.Attribute.chipDelete = global::Test.Droid.Resource.Attribute.chipDelete;
			global::com.android.ex.chips.Resource.Attribute.chipEntryErrorHint = global::Test.Droid.Resource.Attribute.chipEntryErrorHint;
			global::com.android.ex.chips.Resource.Attribute.chipFontSize = global::Test.Droid.Resource.Attribute.chipFontSize;
			global::com.android.ex.chips.Resource.Attribute.chipHeight = global::Test.Droid.Resource.Attribute.chipHeight;
			global::com.android.ex.chips.Resource.Attribute.chipOverLimitErrorHint = global::Test.Droid.Resource.Attribute.chipOverLimitErrorHint;
			global::com.android.ex.chips.Resource.Attribute.chipPadding = global::Test.Droid.Resource.Attribute.chipPadding;
			global::com.android.ex.chips.Resource.Attribute.disableDelete = global::Test.Droid.Resource.Attribute.disableDelete;
			global::com.android.ex.chips.Resource.Attribute.imageSpanAlignment = global::Test.Droid.Resource.Attribute.imageSpanAlignment;
			global::com.android.ex.chips.Resource.Attribute.invalidChipBackground = global::Test.Droid.Resource.Attribute.invalidChipBackground;
			global::com.android.ex.chips.Resource.Dimension.chip_height = global::Test.Droid.Resource.Dimension.chip_height;
			global::com.android.ex.chips.Resource.Dimension.chip_icon_margin_start = global::Test.Droid.Resource.Dimension.chip_icon_margin_start;
			global::com.android.ex.chips.Resource.Dimension.chip_padding = global::Test.Droid.Resource.Dimension.chip_padding;
			global::com.android.ex.chips.Resource.Dimension.chip_subtitle_padding_start = global::Test.Droid.Resource.Dimension.chip_subtitle_padding_start;
			global::com.android.ex.chips.Resource.Dimension.chip_text_size = global::Test.Droid.Resource.Dimension.chip_text_size;
			global::com.android.ex.chips.Resource.Dimension.chip_title_padding_start = global::Test.Droid.Resource.Dimension.chip_title_padding_start;
			global::com.android.ex.chips.Resource.Dimension.extra_chip_height = global::Test.Droid.Resource.Dimension.extra_chip_height;
			global::com.android.ex.chips.Resource.Dimension.line_spacing_extra = global::Test.Droid.Resource.Dimension.line_spacing_extra;
			global::com.android.ex.chips.Resource.Dimension.padding_no_picture = global::Test.Droid.Resource.Dimension.padding_no_picture;
			global::com.android.ex.chips.Resource.Drawable.chip_background = global::Test.Droid.Resource.Drawable.chip_background;
			global::com.android.ex.chips.Resource.Drawable.chip_background_invalid = global::Test.Droid.Resource.Drawable.chip_background_invalid;
			global::com.android.ex.chips.Resource.Drawable.chip_background_selected = global::Test.Droid.Resource.Drawable.chip_background_selected;
			global::com.android.ex.chips.Resource.Drawable.chip_delete = global::Test.Droid.Resource.Drawable.chip_delete;
			global::com.android.ex.chips.Resource.Drawable.ic_contact_picture = global::Test.Droid.Resource.Drawable.ic_contact_picture;
			global::com.android.ex.chips.Resource.Drawable.list_item_font_primary = global::Test.Droid.Resource.Drawable.list_item_font_primary;
			global::com.android.ex.chips.Resource.Drawable.list_item_font_secondary = global::Test.Droid.Resource.Drawable.list_item_font_secondary;
			global::com.android.ex.chips.Resource.Drawable.no_avatar_picture = global::Test.Droid.Resource.Drawable.no_avatar_picture;
			global::com.android.ex.chips.Resource.Id.baseline = global::Test.Droid.Resource.Id.baseline;
			global::com.android.ex.chips.Resource.Id.bottom = global::Test.Droid.Resource.Id.bottom;
			global::com.android.ex.chips.Resource.Id.end = global::Test.Droid.Resource.Id.end;
			global::com.android.ex.chips.Resource.Id.start = global::Test.Droid.Resource.Id.start;
			global::com.android.ex.chips.Resource.Id.text1 = global::Test.Droid.Resource.Id.text1;
			global::com.android.ex.chips.Resource.Integer.chips_max_lines = global::Test.Droid.Resource.Integer.chips_max_lines;
			global::com.android.ex.chips.Resource.Layout.chips_alternate_item = global::Test.Droid.Resource.Layout.chips_alternate_item;
			global::com.android.ex.chips.Resource.Layout.chips_recipient_dropdown_item = global::Test.Droid.Resource.Layout.chips_recipient_dropdown_item;
			global::com.android.ex.chips.Resource.Layout.copy_chip_dialog_layout = global::Test.Droid.Resource.Layout.copy_chip_dialog_layout;
			global::com.android.ex.chips.Resource.Layout.more_item = global::Test.Droid.Resource.Layout.more_item;
			global::com.android.ex.chips.Resource.String.copy_email = global::Test.Droid.Resource.String.copy_email;
			global::com.android.ex.chips.Resource.String.copy_number = global::Test.Droid.Resource.String.copy_number;
			global::com.android.ex.chips.Resource.String.done = global::Test.Droid.Resource.String.done;
			global::com.android.ex.chips.Resource.String.error_invalid_chips = global::Test.Droid.Resource.String.error_invalid_chips;
			global::com.android.ex.chips.Resource.String.error_over_chips_limit = global::Test.Droid.Resource.String.error_over_chips_limit;
			global::com.android.ex.chips.Resource.String.more_string = global::Test.Droid.Resource.String.more_string;
			global::com.android.ex.chips.Resource.Style.ChipIconStyle = global::Test.Droid.Resource.Style.ChipIconStyle;
			global::com.android.ex.chips.Resource.Style.ChipSubtitleStyle = global::Test.Droid.Resource.Style.ChipSubtitleStyle;
			global::com.android.ex.chips.Resource.Style.ChipTitleStyle = global::Test.Droid.Resource.Style.ChipTitleStyle;
			global::com.android.ex.chips.Resource.Style.RecipientEditTextView = global::Test.Droid.Resource.Style.RecipientEditTextView;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView = global::Test.Droid.Resource.Styleable.RecipientEditTextView;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_avatarPosition = global::Test.Droid.Resource.Styleable.RecipientEditTextView_avatarPosition;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipBackground = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipBackground;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipBackgroundPressed = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipBackgroundPressed;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipDelete = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipDelete;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipEntryErrorHint = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipEntryErrorHint;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipFontSize = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipFontSize;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipHeight = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipHeight;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipOverLimitErrorHint = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipOverLimitErrorHint;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_chipPadding = global::Test.Droid.Resource.Styleable.RecipientEditTextView_chipPadding;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_disableDelete = global::Test.Droid.Resource.Styleable.RecipientEditTextView_disableDelete;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_imageSpanAlignment = global::Test.Droid.Resource.Styleable.RecipientEditTextView_imageSpanAlignment;
			global::com.android.ex.chips.Resource.Styleable.RecipientEditTextView_invalidChipBackground = global::Test.Droid.Resource.Styleable.RecipientEditTextView_invalidChipBackground;
			global::ModernHttpClient.Resource.String.library_name = global::Test.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int GroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int avatarPosition = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int chipBackground = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int chipBackgroundPressed = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int chipDelete = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int chipEntryErrorHint = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int chipFontSize = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int chipHeight = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int chipOverLimitErrorHint = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int chipPadding = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int disableDelete = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int imageSpanAlignment = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int invalidChipBackground = 2130771985;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public const int address_prefix_lr_margin = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int address_prefix_text_size = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int address_prefix_top_margin = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int chip_height = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int chip_icon_margin_start = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int chip_padding = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int chip_subtitle_padding_start = 2130968591;
			
			// aapt resource value: 0x7f04000b
			public const int chip_text_size = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int chip_title_padding_start = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int chips_textfield_lr_margin = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int chips_textfield_minHeight = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int compose_text_top_margin = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int extra_chip_height = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int line_spacing_extra = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int padding_no_picture = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int recipient_tb_padding = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int separator_width = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int subject_textfield_height = 2130968583;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chip_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chip_background_invalid = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chip_background_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chip_delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_contact_picture = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int list_item_font_primary = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list_item_font_secondary = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int no_avatar_picture = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int splash = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int address_suffix = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int baseline = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int bottom = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int end = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int message_field = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int phone_retv = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int start = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int subject_block = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int subject_field = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int text1 = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int chips_max_lines = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chips_alternate_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chips_recipient_dropdown_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chips_recipient_dropdown_item2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int copy_chip_dialog_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int first_view = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int more_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int address_field_prefix = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int copy_email = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int copy_number = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int done = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int error_invalid_chips = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int error_over_chips_limit = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int library_name = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int menu_send_email = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int menu_send_sms = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int menu_show_list = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int message_field_hint = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int more_string = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int recipients_field_hint = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int subject_field_hint = 2131165187;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int ChipIconStyle = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int ChipSubtitleStyle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ChipTitleStyle = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int RecipientEditTextView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_GroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] RecipientEditTextView = new int[] {
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int RecipientEditTextView_avatarPosition = 0;
			
			// aapt resource value: 1
			public const int RecipientEditTextView_chipBackground = 1;
			
			// aapt resource value: 2
			public const int RecipientEditTextView_chipBackgroundPressed = 2;
			
			// aapt resource value: 3
			public const int RecipientEditTextView_chipDelete = 3;
			
			// aapt resource value: 5
			public const int RecipientEditTextView_chipEntryErrorHint = 5;
			
			// aapt resource value: 4
			public const int RecipientEditTextView_chipFontSize = 4;
			
			// aapt resource value: 7
			public const int RecipientEditTextView_chipHeight = 7;
			
			// aapt resource value: 6
			public const int RecipientEditTextView_chipOverLimitErrorHint = 6;
			
			// aapt resource value: 8
			public const int RecipientEditTextView_chipPadding = 8;
			
			// aapt resource value: 9
			public const int RecipientEditTextView_disableDelete = 9;
			
			// aapt resource value: 11
			public const int RecipientEditTextView_imageSpanAlignment = 11;
			
			// aapt resource value: 10
			public const int RecipientEditTextView_invalidChipBackground = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
